[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.12,<3.13"
name = "uplift"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    "datasets",
    "huggingface-hub",
    "fsspec",
    "numpy",
    "ipython>=8.10",
    "jupyterlab>=3.0",
    "notebook",
    "kedro~=1.3.1",
    "causalml[torch]>=0.16.0",
    "kedro-datasets>=9.3.0",
    "imblearn>=0.0",
    "plotly>=6.7.0",
    "dash>=4.1.0",
    "duecredit>=0.11.2",
    "kaleido>=1.3.0",
    "umap-learn>=0.5.12",
    "easydict>=1.13",
    "polars>=1.40.1",
    "pyarrow>=24.0.0",
    "pytest>=7.4.4",
    "pydantic>=2.13.4",
    "econml>=0.16.0",
    "scikit-uplift>=0.5.1",
    "ruff>=0.12.12",
]

[project.scripts]
"uplift" = "uplift.__main__:main"

[project.entry-points."kedro.hooks"]

[project.optional-dependencies]
docs = [
    "docutils<0.21",
    "sphinx>=5.3,<7.3",
    "sphinx_rtd_theme==2.0.0",
    "nbsphinx==0.8.1",
    "sphinx-autodoc-typehints==1.20.2",
    "sphinx_copybutton==0.5.2",
    "ipykernel>=5.3, <7.0",
    "Jinja2<3.2.0",
    "myst-parser>=1.0,<2.1"
]
dev = [
    # "pytest-cov>=3,<7",
    # "pytest-mock>=1.7.1, <2.0",
    "pytest~=7.2",
    "ruff~=0.12.0"
]

[tool.setuptools.dynamic]
version = {attr = "uplift.__version__"}

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.kedro]
package_name = "uplift"
project_name = "uplift"
kedro_init_version = "1.3.1"
tools = "['Linting', 'Testing', 'Custom Logging', 'Documentation', 'Data Structure']"
example_pipeline = "False"
source_dir = "src"

[pytest]
testpaths = "tests"
# [tool.pytest.ini_options]
# addopts = """
# --cov-report term-missing \
# --cov src/uplift -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.ruff.format]
docstring-code-format = true

[tool.ruff]
line-length = 88
show-fixes = true

[tool.ruff.lint]
select = [
    "F",   # Pyflakes
    "W",   # pycodestyle
    "E",   # pycodestyle
    "I",   # isort
    "UP",  # pyupgrade
    "PL",  # Pylint
    "T201", # Print Statement
]
ignore = ["E501"]  # Ruff format takes care of line-too-long

[tool.kedro_telemetry]
project_id = "a6538a505cb04c8192b2c5f4f06ab01c"
